prefix: "!pal"

# A list of modules and the channel their commands will come from
modules:

  general_commands:
    config_path: general.yaml
    channel: null

  class_manager:
    config_path: class-manager.yaml
    channel: ğŸ“class-manager